# -*- coding: utf-8 -*-
"""P -1 .Average temp using List .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9AYpsFOZsY46a9inlNVMH94DO5KM9_k

# Calculate Average Temprature
"""

number_of_days = int(input("How many day's temprature? "))

total = 0

for i in range(1,number_of_days+1):

    next_day = int(input("Day " + str(i) + "'s high temp: "))

    total += next_day
3
average_temp = round(total/number_of_days,2)

print("\n Average = "+ str(average_temp))

# Calculate which day's temprature is higher than average temprature
number_of_days = int(input("How many day's temprature? "))

total = 0
temp = []
for i in range(number_of_days):

    next_day = int(input("Day " + str(i+1) + "'s high temp: "))
    temp.append(next_day)
    total += temp[i]

average_temp = round(total/number_of_days,2)

print("\n Average Temprature= "+ str(average_temp))

above = 0

for i in temp:
    if i>average_temp:
        above+=1

print(str(above)+" day(s) above average temprature")

